version: '3.3'

services:
    tomcat:
        image: 'tomcat:9.0-jdk11'
        depends_on: 
            - db
        ports: 
            - '8080:8080'
        volumes:
            - './target:/usr/local/tomcat/webapps'
            - './tmp/logs/:/usr/local/tomcat/logs'
