version: '3.3'

services:
    tomcat:
        image: 'tomcat:9.0-jdk11'
        depends_on: 
            - db
        ports: 
            - '8080:8080'
        volumes:
            - './target:/usr/local/tomcat/webapps'
            - './tmp/logs/:/usr/local/tomcat/logs'

    db:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: jee
            MYSQL_USER: user
            MYSQL_PASSWORD: password


    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        ports: 
            - "8081:80"
